# Generated by Django 4.2.5 on 2023-09-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='canStock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fechaingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioComun',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioMayoreo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamaño',
        ),
    ]
