# Generated by Django 4.2.5 on 2023-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_comentarios_task_notastarea_task_estadotarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVenta', models.DateTimeField(blank=True, null=True)),
                ('totalVenta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
