# Generated by Django 4.2.5 on 2023-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField(blank=True, null=True)),
                ('totalCompra', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
