# Generated by Django 4.2.5 on 2023-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentesLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaIncidente', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reportadopor', models.IntegerField(blank=True, null=True)),
                ('tipoIncidente', models.TextField(blank=True, null=True)),
                ('accionesCorrectivas', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
