# Generated by Django 4.2.4 on 2023-10-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prioridad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
