# Generated by Django 4.2.4 on 2023-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_task_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
