# Generated by Django 4.2.4 on 2023-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_orden_idcliente_orden_idempleado_orden_totalorden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='FechaVenta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
