# Generated by Django 4.2.4 on 2023-10-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_orden_fechaorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
