# Generated by Django 4.2.4 on 2023-10-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_compra_idempleado_compra_idproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
