# Generated by Django 4.2.4 on 2023-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_ticket_idcliente_alter_ticket_idempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='idCliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='idEmpleado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
