# Generated by Django 4.2.4 on 2023-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_alter_ticket_idcliente_alter_ticket_idempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opionion',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
