# Generated by Django 4.2.5 on 2023-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_task_empleado_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='NotasTarea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
