# Generated by Django 4.2.5 on 2023-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_servicio_descripcion_alter_servicio_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fechaMantenimineto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
