# Generated by Django 4.2.5 on 2023-10-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_mantenimiento_idherramienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
    ]
