# Generated by Django 4.2.5 on 2023-10-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_alter_mantenimiento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
