# Generated by Django 4.2.5 on 2023-10-10 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_alter_producto_idproveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipocliente',
            field=models.CharField(blank=True, choices=[('Mayorista', 'Mayorista'), ('Comun', 'Comun')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipoOrden',
            field=models.CharField(blank=True, choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estadoServicio',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estadotarea',
            field=models.CharField(blank=True, choices=[('Iniciada', 'Iniciada'), ('Proceso', 'Proceso')], max_length=100, null=True),
        ),
    ]
