# Generated by Django 4.2.5 on 2023-10-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_remove_servicio_descuento_remove_task_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
    ]
