# Generated by Django 4.2.5 on 2023-10-11 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_orden_idproveedor_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.producto'),
        ),
    ]
