# Generated by Django 4.2.5 on 2023-10-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0056_orden_cantidadproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='precioUnitario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotalProductos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
