# Generated by Django 4.2.5 on 2023-10-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_orden_preciounitario_orden_subtotalproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='precioUnitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
