# Generated by Django 4.2.5 on 2023-10-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_alter_orden_subtotalproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='subtotalProductos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
