# Generated by Django 4.2.5 on 2023-10-11 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_orden_cantidadproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.servicio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='precioUnitarioProducto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotalProductos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
