# Generated by Django 4.2.5 on 2023-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0063_orden_idservicio_orden_preciounitarioproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cantidadServicios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='precioUnitarioServicios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotalServicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
