# Generated by Django 4.2.5 on 2023-10-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0064_orden_cantidadservicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='totalOrden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
