# Generated by Django 4.2.5 on 2023-10-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0067_herramienta_tipo_alter_opionion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Computadora', 'Computadora'), ('Router', 'Router'), ('Impresora', 'Impresora')], max_length=100, null=True),
        ),
    ]
