# Generated by Django 4.2.5 on 2023-10-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0068_alter_herramienta_proveedor_alter_herramienta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='proveedor',
        ),
    ]
