# Generated by Django 4.2.5 on 2023-10-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0069_remove_herramienta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
