# Generated by Django 4.2.5 on 2023-10-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0071_alter_herramienta_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='idHerramienta',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='responsable',
        ),
    ]
