# Generated by Django 4.2.5 on 2023-10-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0072_remove_mantenimiento_idherramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='idHerramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.herramienta'),
        ),
    ]
