# Generated by Django 4.2.5 on 2023-10-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0074_mantenimiento_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipoMantenimiento',
            field=models.CharField(blank=True, choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Predictivo', 'Predictivo')], max_length=100, null=True),
        ),
    ]
