# Generated by Django 4.2.5 on 2023-10-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0075_alter_mantenimiento_tipomantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Desactivado', 'Desactivado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estadoServicio',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Desactivado', 'Desactivado')], max_length=100, null=True),
        ),
    ]
