# Generated by Django 4.2.5 on 2023-10-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0076_alter_producto_estado_alter_servicio_estadoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
