# Generated by Django 4.2.5 on 2023-10-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0077_alter_ticket_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
