# Generated by Django 4.2.5 on 2023-10-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0078_alter_ticket_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
