# Generated by Django 4.2.5 on 2023-10-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0082_producto_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], max_length=100, null=True),
        ),
    ]
