# Generated by Django 4.2.5 on 2023-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0086_venta_cantidad_venta_cantidadservicio_venta_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
