# Generated by Django 4.2.5 on 2023-11-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0087_venta_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='idOrden',
        ),
    ]
