# Generated by Django 4.2.5 on 2023-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0088_remove_compra_idorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
