# Generated by Django 4.2.5 on 2023-11-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0090_proveedor_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='productos',
        ),
    ]
