# Generated by Django 4.2.5 on 2023-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0091_remove_proveedor_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], max_length=100, null=True),
        ),
    ]
