# Generated by Django 4.2.5 on 2023-11-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0092_compra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
    ]
