# Generated by Django 4.2.5 on 2023-11-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0093_remove_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioMayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
