# Generated by Django 4.2.5 on 2023-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0094_alter_producto_preciomayoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioComun',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
