# Generated by Django 4.2.5 on 2023-11-20 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0095_alter_producto_preciocomun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
