# Generated by Django 4.2.5 on 2023-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0097_remove_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
