# Generated by Django 4.2.5 on 2023-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0105_alter_task_empleado_asignado_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FechaVenta',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
