# Generated by Django 4.2.5 on 2024-01-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0107_alter_cliente_tipocliente_alter_compra_totalcompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='empleado_asignado',
        ),
    ]
