# Generated by Django 4.2.5 on 2024-01-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0108_remove_task_empleado_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estadotarea',
            field=models.CharField(blank=True, choices=[('Iniciada', 'Iniciada'), ('Proceso', 'Proceso'), ('Terminada', 'Terminada')], max_length=100, null=True),
        ),
    ]
