# Generated by Django 4.2.5 on 2024-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_alter_task_estadotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
