# Generated by Django 4.2.5 on 2024-01-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0110_cliente_apellidom_cliente_apellidop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidom',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidop',
        ),
    ]
