# Generated by Django 4.2.5 on 2024-01-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0112_cliente_materno_cliente_paterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='materno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='paterno',
            field=models.CharField(max_length=50),
        ),
    ]
