# Generated by Django 4.2.5 on 2024-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0115_alter_mantenimiento_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentelaboral',
            name='tipoIncidente',
            field=models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=100, null=True),
        ),
    ]
