# Generated by Django 4.2.5 on 2024-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0117_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentelaboral',
            name='horaIncidente',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
