# Generated by Django 4.2.5 on 2024-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0118_alter_incidentelaboral_horaincidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentelaboral',
            name='horaIncidente',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
